name: biodiversite_env
channels:
    - defaults
    - conda-forge
dependencies:
    - numpy
    - pandas
    - shapely
    - ipywidgets
    - requests
    - IPython
    - voila
    - warnings
    - pip:
        - geopandas
        - folium
